### ISSUE TITLE
Does not render

### ISSUE THREAD

**Issue by pkbullock** [n8design/panthema#2]
Hi Stefan, 

I was checking out the web part from your blog in my TR tenant and the web part does not render.
In console i get: 
```
Uncaught (in promise) TypeError: e.indexOf is not a function
    at panthema-web-part_da4fbadc87dce7f9b710ec27849f87df.js:1
    at Array.filter (<anonymous>)
    at t.themeColors (panthema-web-part_da4fbadc87dce7f9b710ec27849f87df.js:1)
    at t.render (panthema-web-part_da4fbadc87dce7f9b710ec27849f87df.js:1)
    at t._renderWithAccessibleTitle (sp-pages-assembly_en-gb_8a614510d7944d55da517d44580c9e17.js:21)
    at sp-pages-assembly_en-gb_8a614510d7944d55da517d44580c9e17.js:21
```
![panthema error](https://user-images.githubusercontent.com/8781041/73065026-72cacb00-3e9a-11ea-8824-d9e3da6b5b71.png)

I am running 1.0.1. I'm running in Edge Beta.

**Comment by StfBauer** [comment]
Thanks @pkbullock Will look into it. Meanwhile event the final version has been removed.

**Comment by Timhaka** [comment]
If you want to get it working you could always do a small quick fix. Clone code and then you can just add the following to the PanthemaWebPart.ts in the themecolor function, you will have to cast the toString on color to make sure its a string and not a number. i did this to just get it to work

```
const colorUsage = colorBlocksValues.filter(
      (color, index, self) => {
        color = color.toString();

        return self.indexOf(color) === index
          && color.indexOf('ms-font') === -1
          && color.indexOf('none') === -1;
      }
    ).map(
      colorValue => {
        console.log('Color USAGE::::');

        let usage = themeSlotKeys.filter(key => {
          return themeSlots[key] === colorValue;
        });

        return {
          color: colorValue,
          usage: usage,
          usagestring: usage.join(', ')
        };
      }
    );
```

**Comment by StfBauer** [comment]
@Timhaka Thank you for your fix. Will try it out and publish a new version of it. In general I also take PR. 😃
